
export const OUTCOME_TAGS = [
  "Clarity Gained",
  "Self Awareness Unlocked",
  "Identity Defined",
  "Future Defined",
  "Direction Set",
  "Plan Mapped",
  "Execution Path Created",
  "Skill Acquired",
  "Capability Built",
  "Belief Shift Achieved",
  "Confidence Activated",
  "Positioning Established",
  "Message Refined",
  "Content System Built",
  "Voice Activated",
  "Offer Defined",
  "Value Packaged",
  "Momentum Built",
  "Consistency Activated",
  "Discipline Installed",
  "System Followed",
  "Progress Measured",
  "Next Level Unlocked",
  "Entry Secured",
  "First Opportunity Landed",
  "Role Acquired"
];
